---
# https://taskfile.dev
version: '3'

tasks:
  default:
    cmds:
        - echo "Hello, World!"

  template:default:
    cmds:
        - helm template charts/tangle > manifests.yaml
        - kubeconform manifests.yaml

  tests:
    dir: examples
    sources:
    - "*.yaml"
    cmds:
      - for: sources
        cmd: helm template ../charts/tangle -f {{ .ITEM }} > manifests.{{ .ITEM  }}
      - defer: rm manifests*
      - kubeconform manifests.*

  docs:
    dir: charts/tangle
    cmds:
      - helm-docs
