apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tangle.fullname" . }}
data:
  tangle.yaml: |-
    listWorkers: {{ .Values.tangle.listWorkers }}
    manifestWorkers: {{ .Values.tangle.manifestWorkers }}
    hardRefreshWorkers: {{ .Values.tangle.hardRefreshWorkers }}
    argocds:
    {{- toYaml .Values.tangle.argoCDs | nindent 6 }}
    {{- if gt (len .Values.tangle.sortOrder) 0 }}
    sortOrder:
    {{- range .Values.tangle.sortOrder }}
    - {{ . }}
    {{- end }}
    {{- end}}